image: archlinux
packages:
  - cargo
  - clang
  - pkgconf
sources:
  - https://git.sr.ht/~nixgoat/shoelace
tasks:
  - build: |
      cd shoelace
      cargo build --release
  - test: |
      cd shoelace
      cargo test --release
