image: debian/testing
packages:
  - cargo
  - clang
  - libssl-dev
  - pkg-config
  - rustfmt
sources:
  - https://git.sr.ht/~nixgoat/shoelace
tasks:
  - build: |
      cd shoelace
      cargo build --release
  - test: |
      cd shoelace
      cargo test --release
