[package]
name = "shoelace"
version = "0.1.0"
edition = "2021"
authors = ["Lux Aliaga <lux@nixgoat.me>"]
repository = "https://git.sr.ht/~nixgoat/shoelace"
license = "GPL-3.0-or-later"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6"
actix-web = "4"
actix-web-static-files = "4.0"
base64 = "0.22"
blake2 = "0.10"
clap = { version = "4.5.4", features = ["derive"] }
config = "0.14"
futures = "0.3.30"
include_dir = { version = "0.7", features = ["glob"] }
infer = "0.15"
lazy_static = "1.4"
reqwest = "0.12"
redis = { version="*", features = ["tokio-comp"] }
rocksdb = { version = "0.22", features = ["multi-threaded-cf"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
spools = "0.5"
static-files = "0.2.1"
tera = "1"
thiserror = "1.0"
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1"
tracing-actix-web = "0.7"
tracing-subscriber = "0.3"

[build-dependencies]
static-files = "0.2.1"
