[package]
name = "shoelace"
version = "0.1.0"
edition = "2021"
authors = ["Lux Aliaga <lux@nixgoat.me>"]
repository = "https://git.sr.ht/~nixgoat/shoelace"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
anyhow = "1.0"
base64 = "0.22"
blake2 = "0.10"
futures = "0.3"
infer = "0.15"
reqwest = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
spools = "0.1"
tera = "1"
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1"
tracing-actix-web = "0.7"
tracing-subscriber = "0.3"
